language: go

go:
    - 1.2
    - 1.3
    - tip

services:
    - mysql

before_install:
    - mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot
    - psql -c "CREATE DATABASE test;" -U postgres

install:
    - go get -t ./...
    - go install ./...

script:
    - go test -v ./...
    - bash test-integration/postgres.sh
